version: 0.15.15.1.{build}
branches:
  only:
  - caffe-0.15-win
clone_folder: c:\project\caffe
environment:
  MSVC_VERSION: 14
  CMAKE_CONFIG: Release
  PYTHON_VERSION: 2
  CUDA_VER: 10
  USE_PREBUILD_VCPKG: 1
  matrix:
  - WITH_CUDA: 1
  - WITH_CUDA: 0
build_script:
- cmd: call scripts\build_windows.cmd
artifacts:
- path: build\install
  name: caffe
